portfolio/urls.py
from django.urls import path
from .views import *


app_name = 'portfolio_app'

urlpatterns = [
    path('', ProjectListView.as_view(), name='portfolio'),
    path('blog-detail/<slug>/', ProjectDetailView.as_view(), name='blog_detail')
]

webpersonal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('about-me/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),
    path('blog/', include('portfolio.urls')),
]

# Solo añadimos esto en modo de desarrollo
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

portfolio/models.py
from django.db import models
from django.template.defaultfilters import slugify

from cloudinary.models import CloudinaryField
from ckeditor.fields import RichTextField

class Project(models.Model):
    title = models.CharField(max_length=200, verbose_name="Titulo")
    descrption = models.TextField(verbose_name="Descripción")
    content = RichTextField('contenido')
    image = CloudinaryField('image', blank=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated =   models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")
    slug = models.SlugField(editable=False, max_length=300)

    class Meta:
        verbose_name = "proyecto"
        verbose_name_plural = "proyectos"
        ordering = ["-created"]

    def __str__(self) -> str:
        return self.title
    
    def save(self, *args, **kwargs):
        slug_unique = '%s' % (self.title)
        self.slug = slugify(slug_unique)
        super(Project, self).save(*args, **kwargs)

core/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404

# Create your views here.
def home(request):
    return render(request, "core/home.html")

def about(request):
    return render(request, "core/about.html")

def portfolio(request):
    return render(request, "core/portfolio.html")

def contact(request):
    return render(request, "core/contact.html")
    

portfolio/views.py
from django.shortcuts import render
from .models import Project
from django.views.generic import ListView, DetailView


# Create your views here.

app_name = 'portfolio_app'

class ProjectListView(ListView):
    model = Project
    template_name = "portfolio/project_list.html"
    context_object_name = 'proyectos'
    ordering = ['-created']


class ProjectDetailView(DetailView):
    model = Project
    template_name = "portfolio/project_detail.html"
    context_object_name = 'proyecto'

core/templates/core/about.html
{% extends 'core/base.html' %}

{%block title %}Acerca de{% endblock %}

{% block background %}https://res.cloudinary.com/dqa2kd0vc/image/upload/v1723239826/Recorriendo-Chapingo_lbpxsy.jpg{% endblock %}

{% block headers %}
<h1>Acerca de</h1>
<span class="subheading">Jonathan Danae Flores Franco</span>
{% endblock %}

{%block content %}
<div class="row">
  <div class="col-lg-3 col-md-4 offset-lg-1">
    <img class="img-fluid avatar" src="https://res.cloudinary.com/dqa2kd0vc/image/upload/v1723225518/photo_ogspqh.jpg" alt="">
  </div>
  <div class="col-lg-7 col-md-8">
    <h2 class="section-heading">Mi Pasión por la Mecatrónica</h2>   
    <p style="text-align: justify;">
        Como ingeniero mecatrónico, mi vida gira en torno a la tecnología y la innovación. Me apasiona la programación y los proyectos de código abierto, disfruto encontrando soluciones creativas a los desafíos en los sectores industrial y agrícola. Mi enfoque integral combina conocimientos de mecánica, hidráulica, neumática, electrónica, control e informática.
    </p>
    <p style="text-align: justify;">
        Además de la ingeniería, soy un gran amante de la música, especialmente del rock progresivo italiano. ¡Recomiendo darle una oportunidad!
    </p>
    <p style="text-align: justify;">
        Soy una persona colaborativa y me adapto fácilmente a diferentes entornos. Estoy emocionado por comenzar mi carrera y contribuir al mundo de la ingeniería con creatividad y dedicación.
    </p>
    <p style="text-align: justify;">
        Mi objetivo es formar parte de equipos multidisciplinarios donde pueda aplicar y fortalecer mis habilidades como desarrollador Python y como ingeniero mecatrónico. Busco proyectos que requieran una combinación de habilidades técnicas y creativas para poder crecer profesionalmente.
    </p>
  </div>
</div>
{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>
<html lang="es">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{%block title %}{% endblock %} | Jonathan Flores</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.10.0/styles/tokyo-night-dark.min.css" integrity="sha512-dSQLLtgaq2iGigmy9xowRshaMzUHeiIUTvJW/SkUpb1J+ImXOPNGAI7ZC8V5/PiN/XN83B8uIk4qET7AMhdC5Q==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.10.0/highlight.min.js" integrity="sha512-6yoqbrcLAHDWAdQmiRlHG4+m0g/CT/V9AGyxabG8j7Jk8j3r3K6due7oqpiRMZqcYe9WM2gPcaNNxnl2ux+3tA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>hljs.highlightAll()</script>
    <!-- Estilos y fuentes del template  -->
    {% load static %}
    <link href="{% static 'core/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'core/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href="{% static 'core/css/clean-blog.min.css' %}" rel="stylesheet">

  </head>

  <body>

    <!-- Navegación -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">Jonathan Flores</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menú
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home' %}">Inicio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">Acerca de</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'portfolio_app:portfolio' %}">Blog</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contact' %}">Contacto</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Cabecera -->
    <header class="masthead" style="background-image: url('{% block background %}https://res.cloudinary.com/dqa2kd0vc/image/upload/v1723225518/home-bg_pkp3ar.jpg{% endblock %}')">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              {% block headers %}{% endblock %}
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Contenido -->
    <div class="container">
      {%block content %}{% endblock %}
    </div>
    
    {% if request.path != "/" %}<hr>{% endif %}
    
    <!-- Pié de página -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <p class="copyright text-muted">Copyright &copy; <span id="current-year"></span></p>
            <script>
              document.getElementById('current-year').textContent = new Date().getFullYear();
            </script>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap y Javascripts -->
    <script src="{% static 'core/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'core/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'core/js/clean-blog.min.js' %}"></script>

  </body>

</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{%block title %}Contacto{% endblock %}

{% block background %}https://res.cloudinary.com/dqa2kd0vc/image/upload/v1723225517/contact-bg_bmuva2.jpg{% endblock %}

{% block headers %}
<h1>Contacto</h1>
<span class="subheading">Asesoría y Servicios</span>
{% endblock %}

{%block content %}
<div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <p style="text-align: justify;">
          Aquí encontrarás mis principales medios de 
          contacto, como mi perfil de LinkedIn, GitHub y correo electrónico.
          <br>
          No dudes en utilizar cualquiera de estas 
          opciones si tienes preguntas o deseas ponerte en contacto conmigo.
        </p>
    </div>
</div>

<footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="mailto:fjonathan785@outlook.com">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-envelope fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="https://github.com/jdfloresf" target="_blank" rel="noopener noreferrer">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="https://www.linkedin.com/in/jflores-franco/" target="_blank" rel="noopener noreferrer">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>

{% endblock %}

core/templates/core/home.html
{% extends 'core/base.html' %}

{%block title %}Portada{% endblock %}

{% block background %}https://res.cloudinary.com/dqa2kd0vc/image/upload/v1723225518/home-bg_pkp3ar.jpg{% endblock %}

{% block headers %}
<h1>Jonathan Flores</h1>
<span class="subheading">Ingeniero Mecatrónico</span>
{% endblock %}

core/templates/core/portfolio.html
{% extends 'core/base.html' %}

{%block title %}Portafolio{% endblock %}

{% block background %}https://res.cloudinary.com/dqa2kd0vc/image/upload/v1723225520/portfolio-bg_zlc7nq.jpg{% endblock %}

{% block headers %}
<h1>Portafolio</h1>
<span class="subheading">Currículo</span>
{% endblock %}

{%block content %}
<!-- Proyecto -->
<div class="row project">  	
	<div class="col-lg-3 col-md-4 offset-lg-1">	      <img class="img-fluid" src="https://res.cloudinary.com/dqa2kd0vc/image/upload/v1723225522/about-bg_twbpdz.jpg" alt="">
	</div>
  <div class="col-lg-7 col-md-8">
		<h2 class="section-heading title">Segundo proyecto</h2>   
    <p>As we got further and further away, it [the Earth] diminished in size. Finally it shrank to the size of a marble, the most beautiful you can imagine. That beautiful, warm....</p>
    <p><a href="{% url 'portfolio_app:project_detail' %}">Más información</a></p>
	</div>
</div>
<!-- Proyecto -->
<div class="row project">  	
	<div class="col-lg-3 col-md-4 offset-lg-1">	      <img class="img-fluid" src="https://res.cloudinary.com/dqa2kd0vc/image/upload/v1723225518/home-bg_pkp3ar.jpg" alt="">
	</div>
  <div class="col-lg-7 col-md-8">
		<h2 class="section-heading title">Primer proyecto</h2>   
    <p>As we got further and further away, it [the Earth] diminished in size. Finally it shrank to the size of a marble, the most beautiful you can imagine. That beautiful, warm....</p>
    <p><a href="{% url 'portfolio_app:project_detail' %}">Más información</a></p>
	</div>
</div>
{% endblock %}

core/templates/portfolio/portfolio_list.html
{% extends 'core/base.html' %}

{%block title %}Portafolio{% endblock %}

{% block background %}https://res.cloudinary.com/dqa2kd0vc/image/upload/v1723225520/portfolio-bg_zlc7nq.jpg{% endblock %}

{% block headers %}
<h1>Portafolio</h1>
<span class="subheading">Currículo</span>
{% endblock %}

{%block content %}
<!-- Proyecto -->
<div class="row project">  	
	<div class="col-lg-3 col-md-4 offset-lg-1">	      <img class="img-fluid" src="https://res.cloudinary.com/dqa2kd0vc/image/upload/v1723225522/about-bg_twbpdz.jpg" alt="">
	</div>
  <div class="col-lg-7 col-md-8">
		<h2 class="section-heading title">Segundo proyecto</h2>   
    <p>As we got further and further away, it [the Earth] diminished in size. Finally it shrank to the size of a marble, the most beautiful you can imagine. That beautiful, warm....</p>
    <p><a href="{% url 'portfolio_app:project_detail' %}">Más información</a></p>
	</div>
</div>
<!-- Proyecto -->
<div class="row project">  	
	<div class="col-lg-3 col-md-4 offset-lg-1">	      <img class="img-fluid" src="https://res.cloudinary.com/dqa2kd0vc/image/upload/v1723225518/home-bg_pkp3ar.jpg" alt="">
	</div>
  <div class="col-lg-7 col-md-8">
		<h2 class="section-heading title">Primer proyecto</h2>   
    <p>As we got further and further away, it [the Earth] diminished in size. Finally it shrank to the size of a marble, the most beautiful you can imagine. That beautiful, warm....</p>
    <p><a href="{% url 'portfolio_app:project_detail' %}">Más información</a></p>
	</div>
</div>
{% endblock %}

core/templates/portfolio/project_detail.html
{% extends 'core/base.html' %}

{% block title %}{{ proyecto.title }}{% endblock %}

{% block background %}https://res.cloudinary.com/dqa2kd0vc/image/upload/v1723225520/portfolio-bg_zlc7nq.jpg{% endblock %}

{% block headers %}
<h1>{{ proyecto.title }}</h1>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <img class="img-fluid" src="{{ proyecto.image.url }}" alt="{{ proyecto.title }}">
        <p>{{ proyecto.content | safe }}</p>
    </div>
</div>
{% endblock %}

core/templates/portfolio/project_list.html
{% extends 'core/base.html' %}

{%block title %}Blog{% endblock %}

{% block background %}https://res.cloudinary.com/dqa2kd0vc/image/upload/v1723225520/portfolio-bg_zlc7nq.jpg{% endblock %}

{% block headers %}
<h1>Blog</h1>
<span class="subheading">Entradas</span>
{% endblock %}

{%block content %}
<!-- Proyecto -->
<div class="row project">  	
	{% for proyecto in proyectos %}
		<div class="col-lg-3 col-md-4 offset-lg-1 mb-4">
			<img class="img-fluid" src="{{ proyecto.image.url }}" alt="">
		</div>
	
		<div class="col-lg-7 col-md-8">
			<h2 class="section-heading title">{{ proyecto.title }}</h2>   
    		<p style="text-align: justify;">{{ proyecto.descrption | truncatechars:150 }}</p>
    		<p><a href="{% url 'portfolio_app:blog_detail' proyecto.slug %}">Más información</a></p>
		</div>
	{% endfor %}
		
</div>
{% endblock %}